// @generated by scripts/generate-headless-capabilities.mjs — do not edit manually.
use crate::capabilities::{CapabilityClass, CommandCapability};

pub const UNAVAILABLE_CAPABILITIES: &[CommandCapability] = &[
    CommandCapability {
        command: "add_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "answer_opencode_question",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "approve_codex_command",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "attach_saved_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "bind_native_cli_session",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "broadcast_session_setting",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "browse_directory",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cancel_create_pr_with_ai_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cancel_review_job",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cancel_review_with_ai",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cancel_session_wakeup",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_claude_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_claude_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_claude_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_coderabbit_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_coderabbit_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_coderabbit_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_codex_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_codex_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_codex_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_commandcode_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_commandcode_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_commandcode_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_cursor_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_cursor_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_gh_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_gh_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_gh_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_grok_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_grok_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_grok_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_mcp_health",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_opencode_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_opencode_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_opencode_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_opinionated_plugin_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_pi_cli_auth",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_pi_cli_installed",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_pi_cli_version_exists",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_remote_server_health",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_resumable_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "check_wsl_tool",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cleanup_combined_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cleanup_old_archives",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "cleanup_old_recovery_files",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "clear_message_queue",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "clear_session_history",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "clear_worktree_pr",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "clone_project_to_remote",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "codex_goal_clear",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "codex_goal_get",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "codex_goal_set",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "connect_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "create_commit_with_ai",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "create_folder",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "create_pr_with_ai_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_all_archives",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_archived_session",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_cli_profile",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_context_file",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_folder",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_pasted_image",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "delete_pasted_text",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "dequeue_message",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_and_link_pr",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_claude_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_coderabbit_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_codex_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_commandcode_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_cursor_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_gh_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_grok_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_open_pr_for_branch",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_opencode_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "detect_pi_in_path",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "disconnect_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "enqueue_message",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "fetch_and_merge_base",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "fetch_worktrees_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "generate_context_from_session",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "generate_release_notes",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_advisory_context_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_app_data_dir",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_cli_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_coderabbit_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_codex_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_commandcode_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_gh_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_grok_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_opencode_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_available_pi_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_claude_usage",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_codex_usage",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_commandcode_install_command",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_cursor_install_command",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_dependabot_alert",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_git_poll_interval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_github_branch_url",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_github_remotes",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_github_repo_url",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_grok_install_command",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_http_server_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_issue_context_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_jean_config",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_jean_mcp_config_snippet",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_linear_issue",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_linear_issue_by_number",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_linear_issue_context_contents",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_local_tool_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_mcp_servers",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_merge_conflicts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_opencode_server_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_pr_context_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_pr_prompt",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_pr_review_comments",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_remote_poll_interval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_remote_server_status",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_repository_advisory",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_review_job",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_review_prompt",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_saved_context_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_scheduled_wakeup",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_security_context_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_session_debug_info",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_terminal_listening_ports",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "get_wsl_home_dir",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "greet",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "has_running_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_claude_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_coderabbit_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_codex_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_commandcode_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_gh_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_gh_on_remote",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_grok_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_jean_mcp_config",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_opencode_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_opinionated_plugin",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "install_pi_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "is_wsl_available",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "link_worktree_pr",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_all_archived_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_all_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_archived_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_attached_saved_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_claude_commands",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_claude_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_codex_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_commandcode_models",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_commandcode_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_cursor_models",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_cursor_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_dependabot_alerts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_github_releases",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_grok_models",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_grok_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_http_bind_host_options",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_linear_issues",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_linear_teams",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_loaded_advisory_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_loaded_issue_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_loaded_linear_issue_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_loaded_pr_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_loaded_security_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_native_cli_sessions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_opencode_models",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_opencode_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_pending_wakeups",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_pi_models",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_pi_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_plugin_skills",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_remote_jean_versions",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_remote_servers",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_repository_advisories",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_review_jobs",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_saved_contexts",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_workflow_runs",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "list_wsl_distros",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_advisory_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_emergency_data",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_issue_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_linear_issue_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_older_session_messages",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_pr_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "load_security_alert_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "login_grok_cli_device",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "mark_plan_approved",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "merge_github_pr",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "merge_worktree_to_base",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "move_item",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "move_queued_message_front",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_branch_on_github",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_file_dialog",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_file_in_default_app",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_folder_dialog",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_log_directory",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_project_on_github",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_project_worktrees_folder",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_pull_request",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_worktree_in_editor",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_worktree_in_finder",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "open_worktree_in_terminal",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "prepare_backend_terminal_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "provision_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "read_clipboard_image",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "read_context_file",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "read_file_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "read_pasted_text",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "read_plan_file",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "rebase_worktree",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "regenerate_http_token",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "regenerate_session_name",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_advisory_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_issue_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_linear_issue_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_pr_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_project_avatar",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_queued_message",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_saved_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "remove_security_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "rename_folder",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "rename_saved_context",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "reorder_items",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "report_remote_connection_failure",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "resolve_claude_command",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_command_approval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_dynamic_tool_call",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_file_change_approval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_mcp_elicitation",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_permissions_request",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "respond_codex_user_input_request",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "restore_session_with_base",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "resume_session",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "run_cli_path_update",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "run_coderabbit_review",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "run_review_with_ai",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_cancelled_message",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_cli_profile",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_context_file",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_dropped_image",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_emergency_data",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_jean_config",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_pasted_image",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_pasted_text",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "save_worktree_pr",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "search_linear_issues",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "send_native_notification",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_active_worktree_for_polling",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_all_worktrees_for_polling",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_app_focus_state",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_git_poll_interval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_pr_worktrees_for_polling",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_project_avatar",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_remote_poll_interval",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_backend",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_effort_level",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_last_opened",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_model",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_provider",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_session_thinking_level",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_sessions_last_opened_bulk",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "set_window_vibrancy",
        class: CapabilityClass::DesktopOnly,
        available: false,
    },
    CommandCapability {
        command: "start_background_investigation",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "start_http_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "start_opencode_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "start_review_job",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "steer_codex_turn",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "steer_opencode_turn",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "steer_pi_turn",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "stop_http_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "stop_opencode_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "test_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "track_native_cli_session",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "trigger_coderabbit_pr_review",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "trigger_immediate_git_poll",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "trigger_immediate_remote_poll",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_claude_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_coderabbit_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_codex_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_commandcode_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_gh_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_grok_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_opencode_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_opinionated_plugin",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "uninstall_pi_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_coderabbit_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_commandcode_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_grok_cli",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_pasted_text",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_queued_message",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_remote_server",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "update_session_state",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "validate_http_bind_host",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "write_clipboard_text",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
    CommandCapability {
        command: "write_file_content",
        class: CapabilityClass::AdapterBacked,
        available: false,
    },
];
